CREATE TABLE TRANSACTION (
    ID Integer PRIMARY KEY,
    cardNumber NUMBER,
    TIMESTAMP TIMESTAMP,
    TYPE VARCHAR2(20),
    AMOUNT Integer,
    FOREIGN KEY (cardNumber) REFERENCES ACCOUNT(CARDNUMBER)
);